/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.ServicesMenu;

import DatabaseManager.DatabaseOperations;
import GUI.ButtonHandler;

/**
 *
 * @author Liam
 */
public class ServicesMenuUI extends javax.swing.JFrame {

    /**
     * Creates new form ServicesMenuUI
     */
    
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    
    private static Object[][] rowData;
    
    
    public ServicesMenuUI(Object[][] data) {
        System.out.println("Before data");
        this.rowData = data;
        System.out.println("After Data");
        
        //int rowCount = 0;
        for (Object[] rowData1 : data) {
            for (Object rowData11 : rowData1) {
                //rowData[i][j]=data[i][j];
                System.out.println(rowData11);
            }
        }
        initComponents();
        this.setLocationRelativeTo(null);
    }
        
        
        //System.out.println("Row Data......");
        //System.out.println(rowData[1][1]);
        
    
    public void makeVisible(){
        this.setVisible(true);
    }
    
    public void makeNonVisible(){
        this.setVisible(false);
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        /*
        System.out.println("InitComponents");
        jPanel1 = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        IncludeServicesButton = new javax.swing.JButton();
        jTable1 = new javax.swing.JTable();
        */
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        IncludeServicesButton = new IncludeServicesButton();
        IncludeServicesButton.setFont(new java.awt.Font("Dialog", 0, 14));
        IncludeServicesButton.setText("Include Services");
        
        
        ButtonHandler vf = new ButtonHandler();
        IncludeServicesButton.addActionListener(vf);

        
        System.out.println("Got This far2");
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            
            rowData,
            new String [] {
                 "Service Name", "Service Price", "Add"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class,
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        System.out.println("End of table creation");
        jScrollPane1.setViewportView(jTable1);
        System.out.println("End of table creationwe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addComponent(IncludeServicesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                //.addGap(186, 186, 186) 
                .addContainerGap(185, Short.MAX_VALUE))    
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                //.addContainerGap(272, Short.MAX_VALUE)
                   
                    .addGap(0,0,0)
                .addComponent(IncludeServicesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap()
            )
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap()
            )
        );

        pack(); 
    }          
                         
    
    private javax.swing.JButton IncludeServicesButton;
    //private javax.swing.JPanel jPanel1;
    // End of variables declaration  
    
}

